export const Usuarios = [
  {
    id: 1,
    imagem_perfil: "assets/pessoa/1.jpeg",
    nome_usuario: "Safak Kocaoglu",
  },
  {
    id: 2,
    imagem_perfil: "assets/pessoa/2.jpeg",
    nome_usuario: "Janell Shrum",
  },
  {
    id: 3,
    imagem_perfil: "assets/pessoa/3.jpeg",
    nome_usuario: "Alex Durden",
  },
  {
    id: 4,
    imagem_perfil: "assets/pessoa/4.jpeg",
    nome_usuario: "Dora Hawks",
  },
  {
    id: 5,
    imagem_perfil: "assets/pessoa/5.jpeg",
    nome_usuario: "Thomas Holden",
  },
  {
    id: 6,
    imagem_perfil: "assets/pessoa/6.jpeg",
    nome_usuario: "Shirley Beauchamp",
  },
  {
    id: 7,
    imagem_perfil: "assets/pessoa/7.jpeg",
    nome_usuario: "Travis Bennett",
  },
  {
    id: 8,
    imagem_perfil: "assets/pessoa/8.jpeg",
    nome_usuario: "Kristen Thomas",
  },
  {
    id: 9,
    imagem_perfil: "assets/pessoa/9.jpeg",
    nome_usuario: "Gary Duty",
  },
  {
    id: 10,
    imagem_perfil: "assets/pessoa/10.jpeg",
    nome_usuario: "Safak Kocaoglu",
  },
];

export const Publicacoes = [
  {
    id: 1,
    descricao: "Love For All, Hatred For None.",
    foto: "assets/publicacao/1.jpeg",
    data: "5 mins ago",
    usuario_id: 1,
    n_likes: 32,
    n_comentarios: 9,
  },
  {
    id: 2,
    foto: "assets/publicacao/2.jpeg",
    data: "15 mins ago",
    usuario_id: 2,
    n_likes: 2,
    n_comentarios: 1,
  },
  {
    id: 3,
    descricao: "Every moment is a fresh beginning.",
    foto: "assets/publicacao/3.jpeg",
    data: "1 hour ago",
    usuario_id: 3,
    n_likes: 61,
    n_comentarios: 2,
  },
  {
    id: 4,
    foto: "assets/publicacao/4.jpeg",
    data: "4 hours ago",
    usuario_id: 4,
    n_likes: 7,
    n_comentarios: 3,
  },
  {
    id: 5,
    foto: "assets/publicacao/5.jpeg",
    data: "5 hours ago",
    usuario_id: 5,
    n_likes: 23,
    n_comentarios: 5,
  },
  {
    id: 6,
    foto: "assets/publicacao/6.jpeg",
    data: "1 day ago",
    usuario_id: 6,
    n_likes: 44,
    n_comentarios: 6,
  },
  {
    id: 7,
    descricao: "Never regret anything that made you smile.",
    foto: "assets/publicacao/7.jpeg",
    data: "2 days ago",
    usuario_id: 7,
    n_likes: 52,
    n_comentarios: 3,
  },
  {
    id: 8,
    foto: "assets/publicacao/8.jpeg",
    data: "3 days ago",
    usuario_id: 8,
    n_likes: 15,
    n_comentarios: 1,
  },
  {
    id: 9,
    descricao: "Change the world by being yourself.",
    foto: "assets/publicacao/9.jpeg",
    data: "5 days ago",
    usuario_id: 9,
    n_likes: 11,
    n_comentarios: 2,
  },
  {
    id: 10,
    foto: "assets/publicacao/10.jpeg",
    data: "1 week ago",
    usuario_id: 10,
    n_likes: 104,
    n_comentarios: 12,
  },
];
